sudo: required
services:
  - docker

before_install:
  - docker build -t react-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true react-docker-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-docker-app"
  env: "ReactDockerApp-env"
  bucket_name: "elasticbeanstalk-us-west-2-192752617941"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


  